# Generated by Django 5.1.5 on 2025-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcategory',
            old_name='role',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(to='base.vendorcategory'),
        ),
    ]
