# Generated by Django 5.1.5 on 2025-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
