# Generated by Django 5.1.5 on 2025-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_eventcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
    ]
