# Generated by Django 5.1.5 on 2025-01-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vendorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorassignment',
            name='role',
        ),
        migrations.AlterField(
            model_name='vendorassignment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='base.vendor'),
        ),
    ]
