# Generated by Django 5.1.5 on 2025-01-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
