# Generated by Django 5.1.5 on 2025-01-26 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_eventregistration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
