# Generated by Django 5.1.5 on 2025-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_eventregistration_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='status',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='type',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='vendor',
        ),
        migrations.AddField(
            model_name='logistics',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment Rentals'), ('catering', 'Catering Services'), ('venue', 'Venue Bookings'), ('transportation', 'Transportation')], default='equipment', max_length=100),
        ),
    ]
