# Generated by Django 5.1.5 on 2025-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_inventory_status_remove_logistics_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='category',
            field=models.CharField(choices=[('Equipment Rentals', 'Equipment Rentals'), ('Catering Services', 'Catering Services'), ('Venue Bookings', 'Venue Bookings'), ('Transportation', 'Transportation')], default='Equipment Rentals', max_length=100),
        ),
    ]
