# Generated by Django 5.1.5 on 2025-01-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_inventorycategory_alter_inventory_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
